Repository ItRecode/recodeIt-client, pull requests merged in 2022-12, with the labels that each got.

#2 [FE-13] PR 리뷰어, 템플릿 설정
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: chore

#3 [FE-14] Tailwind 초기세팅
  package-lock.json
  package.json
  postcss.config.js
  src/App.tsx
  src/index.css
  src/index.tsx
  src/pages/Main/Main.tsx
  src/routes/routes.tsx
  tailwind.config.js
  webpack.config.js
Labels: style, chore

#4 [FE-7] Style: tailwind theme 추가
  tailwind.config.js
Labels: style

#5 [FE-18] assets 절대경로 추가, 뒤로가기 버튼 생성 아이콘 저장
  src/assets/back.svg
  src/components/BackButton.tsx
  tsconfig.extend.json
Labels: feat

#6 [FE-21]chore: 린트 설정
  .eslintrc.js
Labels: chore

#8 [FE-22] prettier-plugin-tailwindcss 설치
  .vscode/settings.json
  package-lock.json
  package.json
Labels: chore

#10 [FE-23] style: tailwind Theme 수정
  public/index.html
  tailwind.config.js
Labels: style

#11 [FE-8] feat: 버튼 컴포넌트 추가
  .eslintrc.js
  src/components/Button.tsx
  src/components/Button/index.tsx
  src/components/Navbar.tsx
  src/index.css
  tailwind.config.js
Labels: feat

#12 [FE-20] feat: 레이아웃 추가
  src/App.tsx
  src/components/Layout.tsx
Labels: feat

#13 [FE-20] fix: 레이아웃 수정
  src/components/Layout.tsx
  tailwind.config.js
Labels: fix

#14 [FE-8] fix: 버튼 컴포넌트 props 속성 추가
  src/components/Button.tsx
Labels: fix

#15 [FE-10] feat: 로그인 페이지 레이아웃 구현
  src/assets/firecracker.svg
  src/assets/google.svg
  src/assets/kakao.svg
  src/pages/Login/GoogleButton.tsx
  src/pages/Login/KakaoButton.tsx
  src/pages/Login/Login.tsx
  src/routes/routes.tsx
  tailwind.config.js
Labels: feat

#17 [FE-30] chore: eslint no-console, index.css에 마진, 패딩 설정
  .eslintrc.js
  src/index.css
Labels: chore

#16 [FE-18] 레코드 추가 페이지 개발, 관련 svg추가
  .eslintrc.js
  package-lock.json
  package.json
  src/assets/cake.svg
  src/assets/camera.svg
  src/assets/celebrate.svg
  src/assets/check.svg
  src/assets/consolate.svg
  src/assets/constant/constant.ts
  src/assets/depress.svg
  src/assets/happy.svg
  src/assets/love.svg
  src/assets/mySide.svg
  src/assets/sympathy.svg
  src/pages/AddRecord/AddRecord.md
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordColor.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/pages/AddRecord/AddRecordTitle.tsx
Labels: feat

#18 [Fe-9] feat: Navbar 컴포넌트 추가
  src/assets/nav_icons/home_icon.svg
  src/assets/nav_icons/myrecord_icon.svg
  src/assets/nav_icons/rank_icon.svg
  src/assets/nav_icons/record_icon.svg
  src/assets/nav_icons/setting_icon.svg
  src/components/Navbar.tsx
  src/components/NavbarItem.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/pages/Rank/Rank.tsx
  src/pages/Setting/Setting.tsx
  src/routes/routes.tsx
Labels: feat

#19 [FE-37] feat: 로컬 스토리지와 Axios 인스턴스 구현
  src/apis/auth.ts
  src/apis/instance.ts
  src/routes/routes.tsx
  src/utils/localStorage.ts
  tsconfig.extend.json
Labels: feat

#20 [FE-31] feat: 카카오 인가코드 받아오기 구현
  src/pages/Login/KakaoButton.tsx
  src/pages/Login/Login.tsx
Labels: feat

#22 [FE-32] feat: 구글 인가코드 받아오기 구현
  src/pages/Login/GoogleButton.tsx
  src/pages/Login/KakaoButton.tsx
  src/pages/Login/Login.tsx
Labels: feat

#21 [FE-41]feat: 컴포넌트 이관
  src/components/MainCategoryTap.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordInput.tsx
Labels: feat

#23 [FE-44]style: border사라지는 버그수정
  src/index.css
Labels: style

#25 [FE-34] feat: 회원가입(닉네임 설정 페이지)구현
  src/components/Button.tsx
  src/components/Input.tsx
  src/pages/SignUp/SignUp.tsx
  src/routes/routes.tsx
Labels: feat

#28 [FE-54] feat: reset.css를 GlobalStyle로 적용
  src/index.css
Labels: feat

#30 [FE-47]feat: 칩 컴포넌트구현
  src/components/Chip.tsx
  src/pages/AddRecord/AddRecord.tsx
Labels: feat

#29 [FE-46]레코드 아이콘 기능
  src/assets/constant/RecordIcons.ts
  src/assets/record_icons/crown.svg
  src/assets/record_icons/gift.svg
  src/assets/record_icons/heart.svg
  src/assets/record_icons/like.svg
  src/assets/record_icons/lock.svg
  src/assets/record_icons/medal.svg
  src/assets/record_icons/moon.svg
  src/assets/record_icons/music.svg
  src/assets/record_icons/rocket.svg
  src/assets/record_icons/speechbubble.svg
  src/assets/record_icons/trashcan.svg
  src/assets/record_icons/umbrella.svg
  src/assets/record_icons/wine.svg
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordInput.tsx
Labels: feat

#32 [FE-59] feat: Input 컴포넌트 확장 구현
  src/assets/icon_closed.svg
  src/components/Button.tsx
  src/components/Input.tsx
Labels: feat, retactor

#34 [FE-61]feat:NotFound페이지 개발, Button컴포넌트 리팩토링
  src/assets/moon_big.svg
  src/components/Button.tsx
  src/pages/NotFound/NotFound.tsx
Labels: feat, retactor

#31 [FE-49]feat: 파일 추가 기능구현
  src/assets/deleteIcon.svg
  src/pages/AddRecord/AddRecordFile.tsx
Labels: feat

#36 [FE-36] feat: 카카오, 구글 로그인, 회원가입 기능 구현(미완성)
  src/apis/auth.ts
  src/apis/instance.ts
  src/components/Input.tsx
  src/hooks/useLocalStorage.ts
  src/pages/Login/GoogleButton.tsx
  src/pages/Login/KakaoButton.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/[type].tsx
  src/pages/SignUp/SignUp.tsx
  src/react-query/hooks/useAuth.ts
  src/react-query/queryKeys.ts
  src/routes/routes.tsx
  src/types/auth.ts
  src/utils/localStorage.ts
  tsconfig.extend.json
Labels: feat

#33 [FE-60]feat: ProtectedRoute구현
  src/App.tsx
  src/routes/page.ts
  src/routes/protectedRoute.tsx
  src/routes/route.tsx
  src/routes/routes.tsx
Labels: feat

#35 [FE-40] feat: 레코드 상세 페이지 레이아웃 구성
  src/assets/more.svg
  src/components/MoreButton.tsx
  src/index.css
  src/pages/DetailRecord/DetailRecord.tsx
Labels: feat

#38 [FE-33] feat: 닉네임 중복 기능 구현
  src/apis/auth.ts
  src/components/Input.tsx
  src/hooks/useForm.ts
  src/pages/SignUp/SignUp.tsx
  src/react-query/hooks/useAuth.ts
  src/react-query/hooks/useNickname.ts
  src/react-query/queryKeys.ts
Labels: feat

#37 [FE-45]컴포넌트 리팩토링, 페이지 레이아웃 구현
  src/components/Button.tsx
  src/components/Chip.tsx
  src/components/MainCategoryTap.tsx
  src/index.css
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
Labels: feat, retactor

#42 Fix : 라우터 오류 해결
  src/App.tsx
  src/routes/page.ts
  src/routes/route.tsx
  src/routes/router.tsx
Labels: fix

#43 [FE-62]feat:NotService페이지 개발
  src/assets/moon_big.svg
  src/assets/umbrella_big.svg
  src/pages/NotService/NotService.tsx
  src/routes/router.tsx
Labels: feat

#45 [FE-63] feat: 회원가입 기능 구현
  src/apis/auth.ts
  src/apis/instance.ts
  src/pages/Login/[type].tsx
  src/pages/SignUp/SignUp.tsx
  src/react-query/hooks/useAuth.ts
  src/react-query/hooks/useNickname.ts
Labels: feat

#44 [FE-64] feat: 레코드 단건 조회 api 연결, 데이터 렌더링
  src/apis/recordData.ts
  src/assets/chip_icon/cake.svg
  src/assets/chip_icon/celebrate.svg
  src/assets/chip_icon/consolate.svg
  src/assets/chip_icon/happy.svg
  src/assets/chip_icon/index.ts
  src/assets/chip_icon/love.svg
  src/assets/constant/constant.ts
  src/assets/record_icons/index.ts
  src/components/Chip.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/DetailRecord/DetailRecord.tsx
Labels: feat

#46 [FE-25] 로그인, 회원가입, 닉네임 중복 기능 구현
  src/apis/auth.ts
  src/apis/instance.ts
  src/components/Button.tsx
  src/components/Input.tsx
  src/hooks/useForm.ts
  src/hooks/useLocalStorage.ts
  src/pages/Login/GoogleButton.tsx
  src/pages/Login/KakaoButton.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/[type].tsx
  src/pages/SignUp/SignUp.tsx
  src/react-query/hooks/useAuth.ts
  src/react-query/hooks/useNickname.ts
  src/react-query/queryKeys.ts
  src/routes/router.tsx
  src/types/auth.ts
  src/utils/localStorage.ts
  tsconfig.extend.json
Labels: feat
