Repository ItRecode/recodeIt-client, pull requests merged in 2023-03, with the labels that each got.

#250 [FE-209] feat: 로그아웃 구현
  src/apis/auth.ts
  src/pages/Setting/Setting.tsx
  src/react-query/hooks/useUser.ts
Labels: ✨ Feature

#252 [FE-234] feat: 추억레코드 캘린더 API 연동 구현
  src/apis/myRecord.ts
  src/pages/MyRecord/Calendar/Calendar.tsx
  src/pages/MyRecord/Calendar/CalendarMonthYear.tsx
  src/pages/MyRecord/Calendar/CalendarRecord.tsx
  src/pages/MyRecord/Calendar/DateBox.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/react-query/hooks/useMemoryRecord.ts
  src/react-query/hooks/useMyRecordByMonthYear.ts
Labels: ✨ Feature, 🔨 Refactor

#253 [FE-254] fix: 팀소개, 피드백 메일 페이지 버그 수정
  src/pages/Setting/FeedbackMail/FeedbackMail.tsx
  src/pages/Setting/TeamIntroduction/TeamIntroduction.tsx
Labels: 🐞 Bug

#251 [FE-246]feat: 내 댓글 관리페이지 개발
  src/pages/Setting/ManageComment/CommentSection.tsx
  src/pages/Setting/ManageComment/ManageComment.tsx
Labels: ✨ Feature

#255 [FE-254] fix: 20글자 넘어가면 return 로직 추가. 메인페이지 랭킹 폰트색 고정. 팀소개 페이지 p태그 폰트 지정
  src/components/RankingItem.tsx
  src/pages/Setting/FeedbackMail/FeedbackMail.tsx
  src/pages/Setting/TeamIntroduction/TeamIntroduction.tsx
Labels: 🐞 Bug

#254 [FE-239]fix: 12글자 넘어가면 입력가능함
  src/pages/AddRecord/AddRecordInput.tsx
Labels: 🐞 Bug

#257 [FE-255] feat: 내 정보 수정 정책 반영
  src/pages/Setting/ModifyInfo/ModifyInfo.tsx
Labels: ✨ Feature

#258 [FE-258] fix: 닉네임 수정 중복검사 추가
  src/pages/Setting/ModifyInfo/ModifyInfo.tsx
Labels: 🐞 Bug

#259 fix: 피드백페이지 qa 반영
  src/pages/Setting/FeedbackMail/FeedbackMail.tsx
Labels: 🐞 Bug

#260 fix: 모아보기 랭킹 기간 변경
  src/assets/constant/ranking.ts
  src/pages/Collect/CollectRanking.tsx
  src/store/collectPageAtom.ts
Labels: 🐞 Bug

#261 [FE-259] fix: url로 직접 닉네임 수정 페이지 접근 시 에러 버그 픽스
  src/pages/Setting/ModifyInfo/ModifyInfo.tsx
Labels: 🐞 Bug

#263 fix: 모아보기 랭킹 기준 시간 추가
  src/pages/Collect/CollectRanking.tsx
Labels: ✨ Feature

#262 [FE-250]feat: 내 댓글 관리 개발
  src/apis/reply.ts
  src/assets/settings_icon/check_box.svg
  src/assets/settings_icon/reply_check.svg
  src/components/SmallToast.tsx
  src/pages/Setting/ManageComment/CommentSection.tsx
  src/pages/Setting/ManageComment/ManageComment.tsx
  src/types/replyData.ts
  src/utils/getFormattedDate.ts
Labels: ✨ Feature

#266 hotfix: 피드백메일 버튼 모바일 감지 추가
  src/pages/Setting/FeedbackMail/FeedbackMail.tsx
Labels: 🐞 Bug

#268 [main] hotfix: 브랜치 수정 내용 develop 반영
  src/pages/Setting/FeedbackMail/FeedbackMail.tsx
  src/pages/Setting/Setting.tsx
Labels: 🎁 Delivery

#267 [FE-250]fix: 내 댓글관리 로딩상태 추가
  src/pages/Setting/ManageComment/ManageComment.tsx
Labels: 🐞 Bug

#269 [FE-244] feat: 탈퇴하기 첫 페이지 레이아웃 구현
  src/pages/Setting/Setting.tsx
  src/pages/Setting/Withdraw/Withdraw.tsx
Labels: ✨ Feature

#270 [FE-252] feat: 탈퇴하기 닉네임 일치 구현
  src/components/Alert.tsx
  src/pages/Setting/Setting.tsx
  src/pages/Setting/Withdraw/CheckedNicknameBeforeWithDraw.tsx
  src/pages/Setting/Withdraw/Withdraw.tsx
  src/routes/router.tsx
Labels: ✨ Feature

#271 [FE-260] feat: 성능 최적화
  src/components/BackButton.tsx
  src/components/Chip.tsx
  src/components/Navbar.tsx
  src/components/NavbarItem.tsx
  src/components/ParrentCategoryTab.tsx
  src/components/RecordCard.tsx
  src/components/Spinner.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/Collect/CollectRanking.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ImageContainer.tsx
  src/pages/DetailRecord/ShareModal.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/Together.tsx
  src/pages/Main/TogetherSlider.tsx
  src/pages/NotRecord/NotRecord.tsx
  src/pages/NotService/NotService.tsx
  src/react-query/hooks/useUser.ts
  src/routes/router.tsx
Labels: ✨ Feature, 🔨 Refactor

#272 [FE-245] feat: 회원탈퇴 api 연결과 구현
  src/apis/auth.ts
  src/assets/close_icon.svg
  src/assets/moon_large.svg
  src/pages/Setting/Withdraw/CheckedNicknameBeforeWithDraw.tsx
  src/pages/Setting/Withdraw/CompletedWithdraw.tsx
  src/react-query/hooks/useUser.ts
  src/routes/protectedRoute.tsx
  src/routes/router.tsx
Labels: ✨ Feature

#273 [FE-260] feat: 설정 페이지 라우터 변경, 상세 페이지 서스펜스 적용
  src/components/Loading.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/routes/router.tsx
Labels: ✨ Feature

#274 [FE-261] feat: 탈퇴 시 재가입불가 화면 구현
  src/assets/heart_large.svg
  src/pages/SignUp/WithdrawSignUp.tsx
  src/react-query/hooks/useAuth.ts
  src/routes/router.tsx
Labels: ✨ Feature

#276 [develop] 상용서버 배포
  src/apis/auth.ts
  src/assets/close_icon.svg
  src/assets/heart_large.svg
  src/assets/moon_large.svg
  src/components/Alert.tsx
  src/components/BackButton.tsx
  src/components/Chip.tsx
  src/components/Loading.tsx
  src/components/Navbar.tsx
  src/components/NavbarItem.tsx
  src/components/ParrentCategoryTab.tsx
  src/components/RecordCard.tsx
  src/components/Spinner.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/Collect/CollectRanking.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ImageContainer.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ShareModal.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/Together.tsx
  src/pages/Main/TogetherSlider.tsx
  src/pages/NotRecord/NotRecord.tsx
  src/pages/NotService/NotService.tsx
  src/pages/Setting/ManageComment/ManageComment.tsx
  src/pages/Setting/Setting.tsx
  src/pages/Setting/Withdraw/CheckedNicknameBeforeWithDraw.tsx
  src/pages/Setting/Withdraw/CompletedWithdraw.tsx
  src/pages/Setting/Withdraw/Withdraw.tsx
  src/pages/SignUp/WithdrawSignUp.tsx
  src/react-query/hooks/useAuth.ts
  src/react-query/hooks/useUser.ts
  src/routes/protectedRoute.tsx
  src/routes/router.tsx
  src/types/replyData.ts
Labels: 🎁 Delivery
