Repository ItRecode/recodeIt-client, pull requests merged in 2023-02, with the labels that each got.

#184 hotfix: 답글 삭제 버그 수정, 답글열기 버그 수정
  src/apis/reply.ts
  src/hooks/useScrollCommentId.ts
  src/pages/DetailRecord/InputAddImage.tsx
  src/pages/DetailRecord/InputSnackBar.tsx
  src/pages/DetailRecord/NestedReplyItem.tsx
  src/pages/DetailRecord/NestedReplyList.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/react-query/hooks/useGetReply.ts
Labels: 🐞 Bug

#185 [FE-185]feat: GA심기
  public/index.html
Labels: 📃 Docs

#186 fix: input placeholder 두줄 버그 수정
  src/pages/DetailRecord/ReplyInput.tsx
Labels: 🐞 Bug

#188 [FE-183] feat: 댓글/답글 작성시 자동 스크롤, refactor: 상세 페이지 컴포넌트 분리 및 리팩토링
  src/hooks/useScrollCommentId.ts
  src/pages/DetailRecord/InputTextarea.tsx
  src/pages/DetailRecord/NestedReplyList.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/MyRecord/MemoryRecordItem.tsx
  src/store/atom.ts
  src/types/replyData.ts
Labels: ✨ Feature, 🐞 Bug, 🔨 Refactor

#189 [FE-178]refactor: 파일 다중 추가, 추가시 UI반영 안되는 버그 수정
  src/pages/AddRecord/AddRecordFile.tsx
Labels: 🐞 Bug, 🔨 Refactor

#190 [FE-186]fix: 탭변경시 사진 초기화 안되는 버그
  src/pages/AddRecord/AddRecordFile.tsx
Labels: 🐞 Bug

#192 [FE-184] feat: 메인페이지 함께 축하해보세요 기능 구현
  src/apis/record.ts
  src/hooks/useSwipe.ts
  src/pages/Main/Main.tsx
  src/pages/Main/TogethderSlider.tsx
  src/pages/Main/Together.tsx
  src/pages/Main/TogetherTab.tsx
  src/types/recordData.ts
Labels: ✨ Feature

#193 [FE-188]feat: notRecord페이지
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/NotRecord/NotRecord.tsx
  src/routes/router.tsx
Labels: ✨ Feature

#191 [FE-182]refactor,fix: 레코드 추가(수정)페이지 리팩토링
  src/pages/AddRecord/AddRecord.md
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordColor.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/utils/fileSize.ts
Labels: 🐞 Bug, 🔨 Refactor

#194 [FE-190] design: 회원가입 문구 로그인으로 변경
  src/pages/DetailRecord/InputTextarea.tsx
  src/routes/protectedRoute.tsx
Labels: 🧑‍🎨 Style

#195 [FE-181] feat: 믹스레코드 기능 구현
  src/apis/record.ts
  src/pages/Main/Main.tsx
  src/pages/Main/MixRecord.tsx
  src/pages/Main/Together.tsx
  src/pages/Main/TogetherSlider.tsx
  src/types/recordData.ts
Labels: ✨ Feature

#196 [FE-189] fix: 페이지 이동 시 스크롤 Top으로 이동 안되던 버그 픽스
  src/components/ScrollTop.tsx
  src/routes/router.tsx
Labels: 🐞 Bug

#198 [fix] style: 홈화면 디자인 스타일 재구성
  src/components/Navbar.tsx
  src/pages/Main/MixRecord.tsx
  src/pages/Main/TogetherSlider.tsx
Labels: 🧑‍🎨 Style

#197 [release] 상용 서버 배포 - 1차(스프린트 5주차)
  src/apis/record.ts
  src/components/Navbar.tsx
  src/components/ScrollTop.tsx
  src/hooks/useScrollCommentId.ts
  src/hooks/useSwipe.ts
  src/pages/AddRecord/AddRecord.md
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordColor.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/InputTextarea.tsx
  src/pages/DetailRecord/NestedReplyList.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/MixRecord.tsx
  src/pages/Main/Together.tsx
  src/pages/Main/TogetherSlider.tsx
  src/pages/Main/TogetherTab.tsx
  src/pages/MyRecord/MemoryRecordItem.tsx
  src/pages/NotRecord/NotRecord.tsx
  src/routes/protectedRoute.tsx
  src/routes/router.tsx
  src/store/atom.ts
  src/types/recordData.ts
  src/types/replyData.ts
  src/utils/fileSize.ts
Labels: 🎁 Delivery

#200 fix: 홈이미지 변경, 함께 축하해보세요 제목 줄바꿈 추가
  src/assets/home_img.svg
  src/pages/Main/Main.tsx
  src/pages/Main/MixRecord.tsx
  src/pages/Main/Together.tsx
  src/pages/Main/TogetherSlider.tsx
Labels: 🐞 Bug

#199 [FE-191] style: og태그 내용 변경
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: 📃 Docs

#201 [Develop] : 상용서버 재배포
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/assets/home_img.svg
  src/pages/Main/Main.tsx
  src/pages/Main/MixRecord.tsx
  src/pages/Main/Together.tsx
  src/pages/Main/TogetherSlider.tsx
Labels: 🎁 Delivery

#202 hotfix: 탭 padding 추가, 이미지 링크 추가, 글자수 변경
  src/pages/Main/Main.tsx
  src/pages/Main/Together.tsx
  src/pages/Main/TogetherSlider.tsx
Labels: 🐞 Bug

#204 hotfix: 모바일 감지 추가
  src/hooks/useCheckMobile.ts
  src/pages/Main/TogetherSlider.tsx
Labels: 🐞 Bug

#205 Fix : 핫픽스 develop 브랜치 반영
  src/pages/Main/Main.tsx
  src/pages/Main/Together.tsx
  src/pages/Main/TogetherSlider.tsx
Labels: 🐞 Bug

#206 [FE-195] fix: 믹스레코드 버그 수정
  src/assets/constant/constant.ts
  src/pages/Main/Main.tsx
  src/pages/Main/MixRecord.tsx
  src/pages/Main/Together.tsx
  src/pages/Main/TogetherSlider.tsx
  src/pages/Main/TogetherTab.tsx
  src/types/category.ts
Labels: 🐞 Bug

#209 [FE-205] refactor: addRecord 페이지 1차 리팩토링
  src/apis/share.ts
  src/components/Category.tsx
  src/components/MainCategoryTap.tsx
  src/components/ParrentCategoryTab.tsx
  src/pages/AddRecord/AddRecord.md
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordColor.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/EditModal.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/ParrentCategoryTab.tsx
  src/pages/Main/Ranking.tsx
  src/pages/Main/Together.tsx
  src/pages/Main/TogetherSlider.tsx
  src/store/atom.ts
  src/utils/localStorage.ts
Labels: 🔨 Refactor

#210 [FE-193] feat: 달력컴포넌트 구현(년, 월 선택은 아직 안됨)
  src/assets/myRecordIcon/close.svg
  src/pages/MyRecord/Calendar.tsx
  src/pages/MyRecord/DateBox.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/pages/MyRecord/MyRecordCalendar.tsx
  src/pages/MyRecord/TodayRecord.tsx
  src/pages/MyRecord/getCalendarDetail.ts
  src/react-query/hooks/useMyRecord.ts
Labels: ✨ Feature

#212 [FE-202] feat: 검색 페이지, 달력 페이지 라우트 구현
  src/pages/MyRecord/Calendar/CalendarRecord.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/pages/MyRecord/MyRecordCalendar.tsx
  src/pages/MyRecord/Search/SearchRecord.tsx
  src/routes/router.tsx
Labels: ✨ Feature

#213 [FE-214]feat: Card컴포넌트화
  src/components/RecordCard.tsx
  src/pages/Main/TogetherSlider.tsx
  src/types/recordData.ts
Labels: ✨ Feature

#211 [FE-213]fix: 레코드 추가페이지 버그 픽스
  src/components/Category.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
Labels: 🐞 Bug

#214 [FE-215] feat: 검색 페이지 레이아웃과 컴포넌트 분리
  src/pages/MyRecord/Calendar/Calendar.tsx
  src/pages/MyRecord/Calendar/DateBox.tsx
  src/pages/MyRecord/Calendar/getCalendarDetail.ts
  src/pages/MyRecord/Common/MemoryRecordCard.tsx
  src/pages/MyRecord/Common/MyRecordCard.tsx
  src/pages/MyRecord/Common/SearchInput.tsx
  src/pages/MyRecord/MemoryRecord.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/pages/MyRecord/Search/SearchRecord.tsx
  src/pages/MyRecord/TodayRecord.tsx
  src/react-query/hooks/useMemoryRecord.ts
  src/react-query/hooks/useRecordByDate.ts
  src/react-query/queryKeys.ts
Labels: ✨ Feature, 🔨 Refactor

#215 [FE-201] feat: 검색 페이지 API 연동과 myRecord 타입과 api 리팩토링
  src/apis/myRecord.ts
  src/apis/record.ts
  src/components/Navbar.tsx
  src/pages/MyRecord/Common/MemoryRecordCard.tsx
  src/pages/MyRecord/Common/MyRecordCard.tsx
  src/pages/MyRecord/Common/SearchInput.tsx
  src/pages/MyRecord/MemoryRecord.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/pages/MyRecord/Search/SearchRecord.tsx
  src/pages/MyRecord/TodayRecord.tsx
  src/react-query/hooks/useMemoryRecord.ts
  src/react-query/hooks/useMyRecordByDate.ts
  src/react-query/hooks/useMyRecordByKeyword.ts
  src/react-query/queryKeys.ts
  src/routes/protectedRoute.tsx
  src/routes/router.tsx
  src/store/myRecordAtom.ts
  src/types/myRecord.ts
  src/types/recordData.ts
  src/types/request.ts
  src/types/response.ts
Labels: ✨ Feature, 🔨 Refactor

#216 [FE-212] fix: 브라우저 작아졌을 때 스크롤 에러 버그 픽스(feat. 메인페이지)
  src/pages/Main/Main.tsx
Labels: 🐞 Bug

#217 [FE-196]feat: 모아보기 레이아웃 구성
  src/apis/record.ts
  src/assets/collect_page_icon/reset.svg
  src/assets/nav_icons/collect_icon.svg
  src/components/Navbar.tsx
  src/components/NavbarItem.tsx
  src/pages/Collect/Collect.tsx
  src/pages/Collect/RecentRecord.tsx
  src/pages/Main/Together.tsx
  src/pages/Rank/Rank.tsx
  src/routes/router.tsx
Labels: ✨ Feature

#218 [FE-218] fix: iconColor 필드 이름 변경으로 colorName으로 수정
  src/pages/MyRecord/Common/MemoryRecordCard.tsx
  src/pages/MyRecord/MemoryRecord.tsx
  src/types/recordData.ts
Labels: 🐞 Bug

#219 [FE-219] feat: 메인페이지 카테고리ID 유지 추가
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/InputSnackBar.tsx
  src/pages/DetailRecord/InputTextarea.tsx
  src/pages/DetailRecord/NestedReplyItem.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/Main/Main.tsx
  src/store/atom.ts
  src/store/detailPageAtom.ts
  src/store/mainPageAtom.ts
Labels: ✨ Feature

#220 [FE-199]feat: 모아보기 API연결, 새로고침 타이머 구현
  src/apis/record.ts
  src/assets/collect_page_icon/reset_disabled.svg
  src/pages/Collect/RecentRecord.tsx
  src/react-query/hooks/useRecentRecord.ts
  src/react-query/queryKeys.ts
  src/utils/getCurrentTime.ts
Labels: ✨ Feature, 🔨 Refactor

#221 [FE-210]fix: 뒤로가기 버튼 수정
  src/assets/constant/others.ts
  src/components/BackButton.tsx
  src/pages/Collect/Collect.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/Main/Main.tsx
  src/react-query/hooks/usePreviousUrlWithStorage.ts
  src/utils/sessionStorage.ts
Labels: ✨ Feature

#222 [FE-220]fix,feat: 스크롤 탑버튼 구현, 모아보기 버그 수정
  src/assets/collect_page_icon/scrollTop.svg
  src/pages/Collect/Collect.tsx
  src/pages/Collect/RecentRecord.tsx
  src/react-query/hooks/useRecentRecord.ts
  src/utils/getCurrentTime.ts
Labels: ✨ Feature, 🐞 Bug

#223 [FE-194] feat: 메인페이지 랭킹
  src/apis/record.ts
  src/assets/ranking_btn_arrow.svg
  src/assets/ranking_down_arrow.svg
  src/components/Category.tsx
  src/pages/Main/Ranking.tsx
  src/pages/Main/RankingList.tsx
  src/types/recordData.ts
Labels: ✨ Feature

#224 [FE-221]fix: QA버그 수정
  src/components/RecordCard.tsx
  src/pages/Collect/Collect.tsx
  src/pages/Collect/RecentRecord.tsx
  src/pages/Main/TogetherSlider.tsx
Labels: 🐞 Bug

#225 [FE-222]feat: 타이머 UI개발
  src/assets/constant/collect.ts
  src/pages/Collect/RecentRecord.tsx
  src/pages/Collect/Timer.tsx
  src/utils/getTimeGap.ts
Labels: ✨ Feature

#227 [FE-198] feat: 모아보기 랭킹
  src/assets/collect_page_icon/collapse.svg
  src/assets/constant/ranking.ts
  src/components/Category.tsx
  src/components/RankingItem.tsx
  src/pages/Collect/Collect.tsx
  src/pages/Collect/CollectRanking.tsx
  src/pages/Collect/PeriodModal.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/RankingList.tsx
Labels: ✨ Feature

#226 fix: 축하, 위로 카테고리 코드 바뀐버그 수정
  src/pages/AddRecord/AddRecordCategory.tsx
Labels: 🐞 Bug

#228 [FE-223] fix: QA 피드백 반영 및 추가
  src/components/Category.tsx
  src/components/RankingItem.tsx
  src/components/RecordCard.tsx
  src/pages/Collect/CollectRanking.tsx
  src/pages/DetailRecord/InputAddImage.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/Main/MixRecord.tsx
  src/pages/Main/RankingList.tsx
Labels: 🐞 Bug

#229 [FE-224] fix: 마이페이지 검색 QA 버그 픽스
  src/assets/constant/constant.ts
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/MyRecord/Common/SearchInput.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/pages/MyRecord/Search/SearchRecord.tsx
Labels: 🐞 Bug

#230 [FE-225]fix: 타이머 버그 픽스
  src/pages/Collect/Timer.tsx
Labels: 🐞 Bug

#232 [FE-227]fix: 새로고침시 상단으로 안가는 버그
  src/pages/Collect/RecentRecord.tsx
  src/react-query/hooks/useRecentRecord.ts
Labels: 🐞 Bug

#234 [FE-229] fix: 메인페이지 & 랭킹 QA 피드백 반영
  src/apis/record.ts
  src/components/Category.tsx
  src/components/RankingItem.tsx
  src/components/RecordCard.tsx
  src/pages/Collect/Collect.tsx
  src/pages/Collect/CollectRanking.tsx
  src/pages/Collect/RecentRecord.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/Ranking.tsx
  src/store/collectPageAtom.ts
  src/store/detailPageAtom.ts
  src/store/mainPageAtom.ts
Labels: 🐞 Bug

#233 [FE-228]fix,feat: 최근 레코드 QA반영
  src/components/RecordCard.tsx
  src/pages/Collect/RecentRecord.tsx
  src/pages/Collect/Timer.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/react-query/hooks/useRecentRecord.ts
Labels: ✨ Feature, 🐞 Bug

#235 [FE-230] fix: 검색 input 포커스 해제 시 placeholder 초기화 버그 픽스
  src/pages/MyRecord/Common/SearchInput.tsx
Labels: 🐞 Bug

#237 fix: 최신레코드 레코드 아이템 크기 조정 이슈 해결
  src/components/RecordCard.tsx
Labels: 🐞 Bug

#238 [FE-208] feat: 달력, 년/월 선택, 레코드 있는 날짜 받아오도록 구현과 날짜 선택
  src/apis/myRecord.ts
  src/index.css
  src/pages/MyRecord/Calendar/Calendar.tsx
  src/pages/MyRecord/Calendar/CalendarMonthYear.tsx
  src/pages/MyRecord/Calendar/CalendarRecord.tsx
  src/pages/MyRecord/Calendar/DateBox.tsx
  src/react-query/hooks/useMyRecordByMonthYear.ts
  src/react-query/hooks/useRecordsByMonthYear.ts
  src/types/myRecord.ts
  src/utils/getFormattedDate.ts
Labels: ✨ Feature

#241 [FE-247] feat: 랭킹 데이터 없는 경우 추가
  src/components/RankingItemNoData.tsx
  src/pages/Collect/CollectRanking.tsx
  src/pages/Main/RankingList.tsx
Labels: ✨ Feature

#242 [FE-248] fix: 수정모드일때 value 바뀌는 기능 추가
  src/pages/DetailRecord/InputTextarea.tsx
  src/pages/DetailRecord/ReplyInput.tsx
Labels: ✨ Feature, 🐞 Bug

#243 [FE-249] feat: 카테고리 스크롤 유지 추가
  src/components/Chip.tsx
  src/pages/Collect/CollectRanking.tsx
  src/pages/Main/RankingList.tsx
Labels: ✨ Feature, 🐞 Bug

#240 [FE-203]feat: 설정페이지 레이아웃 개발 기타 페이지 라우팅
  src/assets/front_white.svg
  src/pages/Setting/FeedbackMail/FeedbackMail.tsx
  src/pages/Setting/ManageComment/ManageComment.tsx
  src/pages/Setting/ModifyInfo/ModifyInfo.tsx
  src/pages/Setting/Setting.tsx
  src/pages/Setting/SettingSection.tsx
  src/pages/Setting/TeamIntroduction/TeamIntroduction.tsx
  src/pages/Setting/Withdraw/Withdraw.tsx
  src/routes/router.tsx
Labels: ✨ Feature

#244 fix: 설정 페이지 라우팅 변경
  src/pages/Setting/Setting.tsx
  src/routes/router.tsx
Labels: 🐞 Bug

#246 [FE-235] fix: 오늘레코드 api 변경으로 연동 구현 수정
  src/apis/myRecord.ts
  src/pages/DetailRecord/DetailRecord.tsx
  src/react-query/hooks/useMemoryRecord.ts
  src/react-query/hooks/useMyRecordByDate.ts
  src/types/myRecord.ts
Labels: ✨ Feature

#247 [FE-233] feat: 피드백메일 레이아웃
  src/pages/Setting/FeedbackMail/FeedbackMail.tsx
Labels: ✨ Feature

#248 [FE-242] feat: 피드백 이메일 api 연동
  package-lock.json
  package.json
  src/components/Toast.tsx
  src/pages/Setting/FeedbackMail/FeedbackMail.tsx
Labels: ✨ Feature
