Repository ItRecode/recodeIt-client, pull requests merged in 2023-01, with the labels that each got.

#48 [FE-70] fix: 닉네임 중복 구현 버그 픽스
  src/pages/SignUp/SignUp.tsx
  src/react-query/hooks/useNickname.ts
Labels: fix

#47 [FE-69] feat: 날짜 전환 로직 구현
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/getCreatedDate.ts
Labels: feat

#51 [FE-68]feat:태그들, GA, favicon
  public/favicon.ico
  public/favicon1.png
  public/index.html
Labels: feat

#50 [FE-65]feat:준비중 페이지와 연결
  src/pages/MyRecord/MyRecord.tsx
  src/pages/NotService/NotService.tsx
  src/pages/Rank/Rank.tsx
  src/pages/Setting/Setting.tsx
Labels: feat

#49 [FE-50]feat: 백엔드 연동, 레코드 추가페이지 완성
  package-lock.json
  package.json
  src/apis/record.ts
  src/assets/constant/RecordIcons.ts
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordColor.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/store/atom.ts
  tsconfig.extend.json
Labels: feat

#52 [FE=75] feat: 로그인/회원가입 세션 적용으로 인한 로컬스토리지 로직 제거
  src/apis/instance.ts
  src/assets/constant/constant.ts
  src/assets/present_box.svg
  src/components/Input.tsx
  src/hooks/useLocalStorage.ts
  src/pages/Login/Login.tsx
  src/react-query/hooks/useAuth.ts
Labels: feat, retactor

#53 [FE-73] 레코드 상세 페이지 댓글 인풋 컴포넌트 구현
  src/assets/plus.svg
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyList.tsx
Labels: feat

#55 [FE-71] fix: 배포 시 에러 버그 픽스
  public/_redirects
  src/apis/record.ts
  src/apis/share.ts
  src/assets/present_box.svg
  src/components/Button.tsx
  src/components/Chip.tsx
  src/components/ShareModal.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/pages/NotService/NotService.tsx
  src/pages/Rank/Rank.tsx
  src/pages/Setting/Setting.tsx
  src/routes/router.tsx
Labels: fix

#56 [FE-78] feat: pointer, property 타입 추가
  src/components/Chip.tsx
Labels: feat, retactor

#58 [FE-77] fix: 닉네임 중복 디자인, 기능 변경 적용
  src/hooks/useDebounce.ts
  src/hooks/useForm.ts
  src/hooks/useTimeoutFunc.ts
  src/pages/SignUp/SignUp.tsx
  src/react-query/hooks/useNickname.ts
Labels: feat, fix

#59 [FE-84] fix: 닉네임 정규식 체크, 자음/모음 정규표현식 추가
  src/pages/SignUp/SignUp.tsx
Labels: feat, fix

#60 [FE-83] fix: 상세페이지, 모달 UI 에러 수정
  src/apis/share.ts
  src/components/Button.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ShareModal.tsx
Labels: fix

#57 [FE-79]feat: 레이아웃 리팩토링
  src/components/Layout.tsx
  src/components/Navbar.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/pages/Login/GoogleButton.tsx
  src/pages/Login/KakaoButton.tsx
  src/pages/Login/Login.tsx
Labels: retactor

#61 [FE-86] fix: 카카오/구글 버튼 아이폰에서만 파란색으로 보이는 버그 픽스
  src/pages/Login/GoogleButton.tsx
  src/pages/Login/KakaoButton.tsx
  tailwind.config.js
Labels: fix

#62 [FE-74]refactor : 코드 리팩토링
  src/apis/record.ts
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordFile.tsx
Labels: retactor

#63 [FE:85] feat: edit 모달 추가, 애니메이션 설정, 상세 페이지 UI 에러 수정
  src/assets/constant/constant.ts
  src/assets/pin.svg
  src/components/Button.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/EditModal.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyList.tsx
  tailwind.config.js
Labels: feat

#64 fix : 상세 페이지 editmodal state 주석 제거
  src/pages/DetailRecord/DetailRecord.tsx
Labels: fix

#66 [FE-88] feat: 글자수 제한, 사진업로드시 아이콘 변경, 레코드 삭제 메시지창 변경
  src/pages/DetailRecord/EditModal.tsx
  src/pages/DetailRecord/ReplyInput.tsx
Labels: feat

#65 [FE-89] 닉네임 정책 변경으로 인한 코드 수정
  src/components/Button.tsx
  src/pages/Login/GoogleButton.tsx
  src/pages/Login/KakaoButton.tsx
  src/pages/Login/Login.tsx
  src/pages/SignUp/SignUp.tsx
Labels: fix, retactor

#67 [FE-87]refactor: QA관련 수정
  src/apis/record.ts
  src/assets/constant/RecordColors.ts
  src/assets/constant/constant.ts
  src/components/Button.tsx
  src/components/MainCategoryTap.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordColor.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/pages/NotFound/NotFound.tsx
  src/pages/NotService/NotService.tsx
Labels: fix, retactor

#68 [FE-91] fix: props -> Props로 변수명 픽스
  src/pages/AddRecord/AddRecordColor.tsx
Labels: fix

#70 [FE-90] fix: 상세 페이지 UI 수정, asset 폴더 정리
  src/assets/chip_icon/depress.svg
  src/assets/chip_icon/index.ts
  src/assets/chip_icon/mySide.svg
  src/assets/chip_icon/sympathy.svg
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/DetailRecord/DetailRecord.tsx
Labels: fix

#69 [FE-92] 레코드 추가 페이지 QA 버그 픽스
  src/assets/constant/RecordIcons.ts
  src/assets/google.svg
  src/assets/kakao.svg
  src/components/Button.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/Login/GoogleButton.tsx
  src/pages/Login/KakaoButton.tsx
  src/pages/SignUp/SignUp.tsx
Labels: fix, retactor

#71 Fix : edit 모달 버튼 크기 오류 수정
  src/pages/DetailRecord/EditModal.tsx
Labels: fix

#73 fix: 카테고리 백 의존성 버그
  src/pages/AddRecord/AddRecordCategory.tsx
Labels: fix

#74 [FE-105] feat: NavBar 탭에 Notservice 디자인 적용
  src/pages/Main/Main.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/pages/Rank/Rank.tsx
  src/pages/Setting/Setting.tsx
Labels: feat

#75 [FE-100]feat: 레코드 추가 버튼 하단 고정
  src/pages/AddRecord/AddRecord.tsx
Labels: feat

#77 fix : 날짜 전환 표기 로직 수정
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/DetailRecord/getCreatedDate.ts
Labels: fix, retactor

#76 [FE-94]feat: 축하 위로 탭 디자인 재적용
  src/components/MainCategoryTap.tsx
  src/pages/AddRecord/AddRecord.tsx
Labels: feat

#79 [FE-98] 로딩 컴포넌트 구현
  src/assets/spinner.svg
  src/components/Loading.tsx
  src/components/Spinner.tsx
Labels: feat

#81 [FE-103] feat: README 1차 수정
  README.md
Labels: etc

#84 [develop] release: 메인 배포 서버로 합치는 작업
  README.md
  public/_redirects
  src/apis/record.ts
  src/apis/share.ts
  src/assets/ImageContainer/left_Arrow.svg
  src/assets/ImageContainer/right_Arrow.svg
  src/assets/chip_icon/depress.svg
  src/assets/chip_icon/index.ts
  src/assets/chip_icon/mySide.svg
  src/assets/chip_icon/sympathy.svg
  src/assets/constant/RecordColors.ts
  src/assets/constant/RecordIcons.ts
  src/assets/constant/constant.ts
  src/assets/google.svg
  src/assets/kakao.svg
  src/assets/pin.svg
  src/assets/present_box.svg
  src/assets/right_purple_arrow.svg
  src/assets/spinner.svg
  src/components/Button.tsx
  src/components/Chip.tsx
  src/components/ImageContainer.tsx
  src/components/Layout.tsx
  src/components/Loading.tsx
  src/components/MainCategoryTap.tsx
  src/components/Navbar.tsx
  src/components/Spinner.tsx
  src/hooks/useDebounce.ts
  src/hooks/useForm.ts
  src/hooks/useImageSwipe.ts
  src/hooks/useTimeoutFunc.ts
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordColor.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/EditModal.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/DetailRecord/ShareModal.tsx
  src/pages/DetailRecord/getCreatedDate.ts
  src/pages/Login/GoogleButton.tsx
  src/pages/Login/KakaoButton.tsx
  src/pages/Login/Login.tsx
  src/pages/Main/Main.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/pages/NotFound/NotFound.tsx
  src/pages/NotService/NotService.tsx
  src/pages/Rank/Rank.tsx
  src/pages/Setting/Setting.tsx
  src/pages/SignUp/SignUp.tsx
  src/react-query/hooks/useNickname.ts
  src/routes/router.tsx
  src/types/recordData.ts
  tailwind.config.js
Labels: release

#83 fix: 상세 페이지 이미지 스와이프 에러 해결
  src/hooks/useImageSwipe.ts
Labels: fix

#85 [FE-108] fix: ouah_token CamelCase로 변경
  src/apis/auth.ts
Labels: fix

#86 [develop] release & fix: 배포 테스트를 위해서 빠른 버그 픽스
  src/apis/auth.ts
  src/hooks/useImageSwipe.ts
Labels: fix

#87 [FE-108] fix: register_session CamelCase로 변경
  src/apis/auth.ts
  src/react-query/hooks/useAuth.ts
Labels: fix, release

#89 [develop] release & fix: 배포 테스트를 위해서 빠른 버그 픽스
  src/apis/auth.ts
  src/react-query/hooks/useAuth.ts
Labels: release

#80 [FE-107]refactor: 사진추가 반영되도록 코드 리팩토링
  src/pages/AddRecord/AddRecord.tsx
Labels: retactor

#93 [FE-101] style: 변수명 수정
  src/components/Modal.tsx
  src/hooks/useClickOutside.ts
Labels: style

#94 [FE-103] feat: 댓글 작성 구현
  src/apis/reply.ts
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ReplyInput.tsx
Labels: feat

#95 [FE-110]bug: 사진 업로드 버그 수정
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordFile.tsx
Labels: fix

#96 [FE-95]feat: protectedRoute 쿠키로 구현
  src/routes/protectedRoute.tsx
  src/routes/router.tsx
Labels: feat

#97 [FE-111]bug: 레코드 파일추가 안했을때 추가 안되는 버그 수정
  src/pages/AddRecord/AddRecord.tsx
Labels: fix

#98 [FE-99] 로그인/회원가입 로딩 컴포넌트와 Spinner 적용
  src/components/Button.tsx
  src/components/Loading.tsx
  src/components/Spinner.tsx
  src/pages/Login/[type].tsx
  src/pages/SignUp/SignUp.tsx
  src/react-query/hooks/useAuth.ts
Labels: feat, retactor

#101 [FE-58] feat: 댓글 작성 구현 & 무한스크롤 구현 및 리액트 쿼리로 로직 리팩토링
  src/apis/record.ts
  src/apis/recordData.ts
  src/apis/reply.ts
  src/hooks/useIntersectionObserver.ts
  src/hooks/useThrottle.ts
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/DetailRecord/getChipIconName.ts
  src/types/replyData.ts
Labels: feat, retactor

#102 [FE-109] 비회원 일 때 레코드 추가 못하도록 알럿 구현
  src/apis/instance.ts
  src/apis/user.ts
  src/assets/constant/constant.ts
  src/components/Navbar.tsx
  src/react-query/hooks/useUser.ts
  src/types/auth.ts
  src/utils/cookies.ts
Labels: feat, retactor

#99 [FE-112]refactor: 텍스트창 색깔 바뀜수정
  src/pages/AddRecord/AddRecordTextArea.tsx
Labels: retactor

#100 [FE-102]refactor: 이미지 1:1비율로 생성도되록
  src/pages/AddRecord/AddRecordFile.tsx
Labels: retactor

#103 [FE-116] style: Spinner 디자인 시스템 적용
  src/components/Button.tsx
  src/components/Spinner.tsx
Labels: feat

#104 [FE-115] 레코드 추가 페이지에서 뒤로가기 시 알럿 노출
  src/components/BackButton.tsx
  src/components/Navbar.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/react-query/hooks/useUser.ts
  src/routes/protectedRoute.tsx
  src/routes/router.tsx
Labels: feat, retactor

#105 Fix: 무한 스크롤 에러 수정
  src/pages/DetailRecord/ReplyList.tsx
Labels: fix

#106 [develop] release: 1차 스프린트 전 쿠키 확인
  package-lock.json
  package.json
  public/index.html
  src/apis/instance.ts
  src/apis/record.ts
  src/apis/recordData.ts
  src/apis/reply.ts
  src/apis/user.ts
  src/assets/constant/RecordIcons.ts
  src/assets/constant/constant.ts
  src/assets/front.svg
  src/components/Alert.tsx
  src/components/BackButton.tsx
  src/components/Button.tsx
  src/components/Loading.tsx
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/components/Spinner.tsx
  src/hooks/useClickOutside.ts
  src/hooks/useIntersectionObserver.ts
  src/hooks/useThrottle.ts
  src/index.css
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordColor.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/DetailRecord/ShareModal.tsx
  src/pages/DetailRecord/getChipIconName.ts
  src/pages/Login/[type].tsx
  src/pages/SignUp/SignUp.tsx
  src/react-query/hooks/useAuth.ts
  src/react-query/hooks/useUser.ts
  src/routes/protectedRoute.tsx
  src/routes/router.tsx
  src/types/auth.ts
  src/types/replyData.ts
  src/utils/cookies.ts
Labels: release

#107 [FE-118] remove: 쿠키 인증 로직 제거
  src/assets/constant/constant.ts
  src/react-query/hooks/useUser.ts
  src/utils/cookies.ts
Labels: fix, retactor

#111 [FE-117]fix: icon들 클릭했을떄 적용안되는 버그 수정
  src/pages/AddRecord/AddRecordIcon.tsx
Labels: fix, retactor

#108 [FE-119] feat: 레코드 추가하기 버튼에 로딩 추가
  src/pages/AddRecord/AddRecord.tsx
Labels: feat, retactor

#109 [FE-120] feat: Axios instance에 timeout 적용
  src/apis/instance.ts
Labels: release

#110 [FE-121] refactor: Alert 컴포넌트 subMessage ReactNode로 수정
  src/components/Alert.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/routes/protectedRoute.tsx
Labels: retactor

#112 [FE-93]feat: 레코드 추가 사진 여러장 구현
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordFile.tsx
Labels: feat, retactor

#113 [develop] release: 실제 버전 배포
  src/apis/instance.ts
  src/assets/constant/constant.ts
  src/components/Alert.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/react-query/hooks/useUser.ts
  src/routes/protectedRoute.tsx
  src/utils/cookies.ts
Labels: release

#114 [FE-125] fix: 공유하기 주소 변경
  src/apis/share.ts
Labels: retactor

#115 [FE-126] fix: 아이콘 이름 모두 소문자로 변경
  src/assets/constant/RecordIcons.ts
Labels: fix

#117 [fix] fix: src안바뀌는 버그
  src/pages/AddRecord/AddRecordIcon.tsx
Labels: fix

#118 [FE-122] fix: 상세 페이지 QA 에러 수정
  src/apis/auth.ts
  src/hooks/useImageSwipe.ts
  src/hooks/useThrottle.ts
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ImageContainer.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/DetailRecord/getCreatedDate.ts
  src/types/replyData.ts
Labels: fix

#119 [FE-127] 레코드 상세 페이지에서 댓글 클릭시 Alert 작업과 1:1비율 재설정
  src/pages/DetailRecord/ImageContainer.tsx
  src/pages/DetailRecord/ReplyInput.tsx
Labels: feat

#120 [FE-128] fix: 레코드 추가 실패할 경우 로딩 재적용
  src/pages/AddRecord/AddRecord.tsx
Labels: fix

#121 [develop] release: 상용 서버 배포(1/16 오후 8시)
  src/apis/auth.ts
  src/apis/share.ts
  src/assets/constant/RecordIcons.ts
  src/hooks/useImageSwipe.ts
  src/hooks/useThrottle.ts
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ImageContainer.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/DetailRecord/getCreatedDate.ts
  src/types/replyData.ts
Labels: release

#122 [FE-129]fix: 200자이상 입력가능 버그 수정
  src/pages/AddRecord/AddRecordTextArea.tsx
Labels: fix

#123 [FE-132] feat: EditModal 모달 밖 클릭 시 닫아지도록 구현
  src/pages/DetailRecord/EditModal.tsx
Labels: retactor

#124 [FE-131]refactor: QA 디테일레코드 부분 반영
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
Labels: feat, fix

#125 [FE-147]fix: 중복 클릭되는 버그 수정
  src/pages/AddRecord/AddRecord.tsx
Labels: fix

#127 [FE-134]feat: 토스트 컴포넌트 구현
  src/components/Toast.tsx
  src/pages/AddRecord/AddRecord.tsx
Labels: feat

#126 [FE-130] fix : 레코드 상세 페이지 QA 에러 수정
  src/apis/auth.ts
  src/components/Button.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ImageContainer.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/DetailRecord/getChipIconName.ts
  src/pages/DetailRecord/getCreatedDate.ts
Labels: fix

#128 [FE-145]feat: 사진 다중 선택
  src/pages/AddRecord/AddRecordFile.tsx
Labels: feat

#130 [FE-137]refactor: 코드 리팩토링
  src/pages/AddRecord/AddRecordCategory.tsx
Labels: retactor

#131 [FE-138]refactor: 훅 사용해서 쓰로틀링구현
  src/hooks/useThrottle.ts
  src/pages/AddRecord/AddRecordIcon.tsx
Labels: retactor

#132 [FE-133]feat: 댓글 사진 5MB추가시 Toast창 띄워주기
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordFile.tsx
Labels: feat, retactor

#136 [FE-151] refactor: Alert 컴포넌트 리팩토링
  src/components/Alert.tsx
Labels: retactor

#133 [FE-114] feat: 대댓글 조회/작성 구현
  src/apis/reply.ts
  src/assets/constant/constant.ts
  src/assets/detail_page_icon/arrow_down.svg
  src/assets/detail_page_icon/arrow_up.svg
  src/index.css
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/NestedReplyList.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/store/atom.ts
  src/types/replyData.ts
  tailwind.config.js
Labels: feat

#134 [FE-140]feat: 레코드 삭제버튼 구현
  src/apis/record.ts
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/EditModal.tsx
Labels: feat

#135 [FE-142] feat: 나만의 추억레코드 API 연동
  src/apis/record.ts
  src/assets/myRecordIcon/arrow_down.svg
  src/assets/myRecordIcon/search.svg
  src/components/Navbar.tsx
  src/components/Spinner.tsx
  src/pages/MyRecord/MemoryRecord.tsx
  src/pages/MyRecord/MemoryRecordItem.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/pages/MyRecord/TodayRecord.tsx
  src/react-query/hooks/useMemoryRecord.ts
  src/react-query/queryKeys.ts
  src/types/recordData.ts
Labels: feat, style, retactor

#138 [FE-149] feat: 나만의 추억 레코드
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/MyRecord/MemoryRecordItem.tsx
  src/types/replyData.ts
Labels: feat

#137 fix: 상세 페이지 이미지 컨테이너 에러 수정
  src/hooks/useImageSwipe.ts
Labels: fix

#139 [FE-143] feat: 댓글 스와이프(드래그 앤 드롭) 구현
  src/assets/myRecordIcon/comment_plus.svg
  src/hooks/useSwipe.ts
  src/pages/MyRecord/MemoryRecordItem.tsx
Labels: feat

#140 [FE-148] feat: 댓글 작성시 새로고침없이 UI 반영 구현
  src/apis/reply.ts
  src/assets/ImageContainer/left_Arrow.svg
  src/assets/ImageContainer/right_Arrow.svg
  src/assets/detail_page_icon/Close.svg
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/ImageContainer.tsx
  src/pages/DetailRecord/ReplyInput.tsx
Labels: feat

#141 [FE-153] refactor: 바뀐 추억 레코드 API 재적용과 Swipe 버그 픽스
  src/apis/record.ts
  src/hooks/useSwipe.ts
  src/pages/MyRecord/MemoryRecord.tsx
  src/pages/MyRecord/MemoryRecordItem.tsx
  src/react-query/hooks/useMemoryRecord.ts
  src/types/recordData.ts
Labels: feat, retactor

#142 [FE-150] feat: 마이 레코드(오늘의 레코드 API 적용)
  src/apis/record.ts
  src/assets/myRecordIcon/calendar.svg
  src/pages/MyRecord/MemoryRecord.tsx
  src/pages/MyRecord/MemoryRecordItem.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/pages/MyRecord/MyRecordCalendar.tsx
  src/pages/MyRecord/TodayRecord.tsx
  src/react-query/hooks/useMemoryRecord.ts
  src/react-query/hooks/useMyRecord.ts
  src/react-query/hooks/useUser.ts
  src/types/recordData.ts
  src/utils/getFormattedDate.ts
Labels: feat, fix

#143 [FE-154] etc: README 추가
  README.md
Labels: 📃 Docs

#144 [FE-155] style: 마이 레코드 커서 포인터 재적용
  src/components/Layout.tsx
  src/pages/MyRecord/MemoryRecordItem.tsx
Labels: 🧑‍🎨 Style

#145 [FE-139]feat: 페이지 수정 기능 구현
  src/apis/record.ts
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordColor.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/EditModal.tsx
  src/utils/localStorage.ts
Labels: ✨ Feature, 🐞 Bug, 🔨 Refactor

#146 [develop] release: 상용 서버 배포
  README.md
  src/apis/auth.ts
  src/apis/record.ts
  src/apis/reply.ts
  src/assets/ImageContainer/left_Arrow.svg
  src/assets/ImageContainer/right_Arrow.svg
  src/assets/constant/constant.ts
  src/assets/detail_page_icon/Close.svg
  src/assets/detail_page_icon/arrow_down.svg
  src/assets/detail_page_icon/arrow_up.svg
  src/assets/myRecordIcon/arrow_down.svg
  src/assets/myRecordIcon/calendar.svg
  src/assets/myRecordIcon/comment_plus.svg
  src/assets/myRecordIcon/search.svg
  src/components/Alert.tsx
  src/components/Button.tsx
  src/components/Chip.tsx
  src/components/Layout.tsx
  src/components/Navbar.tsx
  src/components/Spinner.tsx
  src/components/Toast.tsx
  src/hooks/useImageSwipe.ts
  src/hooks/useSwipe.ts
  src/hooks/useThrottle.ts
  src/index.css
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordColor.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/EditModal.tsx
  src/pages/DetailRecord/ImageContainer.tsx
  src/pages/DetailRecord/NestedReplyList.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/DetailRecord/getChipIconName.ts
  src/pages/DetailRecord/getCreatedDate.ts
  src/pages/MyRecord/MemoryRecord.tsx
  src/pages/MyRecord/MemoryRecordItem.tsx
  src/pages/MyRecord/MyRecord.tsx
  src/pages/MyRecord/MyRecordCalendar.tsx
  src/pages/MyRecord/TodayRecord.tsx
  src/react-query/hooks/useMemoryRecord.ts
  src/react-query/hooks/useMyRecord.ts
  src/react-query/hooks/useUser.ts
  src/react-query/queryKeys.ts
  src/routes/protectedRoute.tsx
  src/store/atom.ts
  src/types/recordData.ts
  src/types/replyData.ts
  src/utils/getFormattedDate.ts
  src/utils/localStorage.ts
  tailwind.config.js
Labels: 🎁 Delivery

#150 [FE-156]fix: 수정 페이지 이동시 버그
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/store/atom.ts
Labels: 🐞 Bug, 🔨 Refactor

#151 [FE-157]fix: url로 화면 빠져나갈때 수정모드 안지워지는 버그
  src/pages/AddRecord/AddRecord.tsx
Labels: 🐞 Bug

#153 [FE-135] feat: 댓글 삭제 구현, 스크롤 에러 수정
  src/apis/reply.ts
  src/assets/constant/constant.ts
  src/assets/sharing_img.svg
  src/components/Alert.tsx
  src/index.css
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/NestedReplyList.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
Labels: ✨ Feature, 🐞 Bug

#152 [FE-158] feat: 추억 레코드 댓글이 없을 경우 UI 구현
  src/pages/MyRecord/MemoryRecordItem.tsx
Labels: ✨ Feature

#154 [fix] fix: svg id값 설정
  src/assets/record_icons/crown.svg
  src/assets/record_icons/gift.svg
  src/assets/record_icons/heart.svg
  src/assets/record_icons/like.svg
  src/assets/record_icons/lock.svg
  src/assets/record_icons/medal.svg
  src/assets/record_icons/moon.svg
  src/assets/record_icons/music.svg
  src/assets/record_icons/rocket.svg
  src/assets/record_icons/speechbubble.svg
  src/assets/record_icons/trashcan.svg
  src/assets/record_icons/umbrella.svg
  src/assets/record_icons/wine.svg
Labels: 🐞 Bug

#158 [FE-163]refactor: 삭제 리팩토링,style: 알럿창 버튼 두개일때 사이에 줄 추가
  src/components/Alert.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/EditModal.tsx
Labels: 🐞 Bug, 🔨 Refactor

#157 [FE-162]fix: 사진 제대로 삭제 안되는 버그 수정, 사진갯수가 0개여도 다음버튼 활성화되는 버그 수정
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/DetailRecord/ImageContainer.tsx
Labels: 🐞 Bug

#156 [FE-160] feat: 비회원일 경우 원래 페이지로 리다이렉트
  src/pages/DetailRecord/ReplyInput.tsx
  src/react-query/hooks/useAuth.ts
  src/routes/protectedRoute.tsx
Labels: ✨ Feature, 🔨 Refactor

#155 [FE-159] fix: 댓글 id값 없을 경우 스크롤 id값 초기화
  src/pages/DetailRecord/ReplyList.tsx
Labels: 🐞 Bug

#161 fix: 레코드 추가페이지 버그 수정
  src/pages/AddRecord/AddRecordFile.tsx
Labels: 🐞 Bug

#159 [FE-164]style: 레코드 추가하기 버튼 sticky 제거
  src/pages/AddRecord/AddRecord.tsx
Labels: 🧑‍🎨 Style

#160 [FE-165] feat: 회원가입 이모지 안들어가도록 구현
  src/components/NavbarItem.tsx
  src/pages/SignUp/SignUp.tsx
Labels: ✨ Feature, 🔨 Refactor

#162 [FE-166] fix: 오늘 레코드가 변경되었을 때 데이터 refetch 구현
  src/pages/MyRecord/MyRecordCalendar.tsx
  src/pages/MyRecord/TodayRecord.tsx
  src/react-query/hooks/useMyRecord.ts
Labels: 🔨 Refactor

#163 [FE-136] feat: 공유하기 form 추가
  public/index.html
  src/apis/reply.ts
  src/apis/share.ts
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/NestedReplyList.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/getCreatedDate.ts
  src/store/atom.ts
Labels: ✨ Feature, 🐞 Bug

#164 [fix] fix: title, description 공백 제거
  public/index.html
Labels: 🐞 Bug

#165 [release] 상용 서버 배포 - 1차
  public/index.html
  src/apis/reply.ts
  src/apis/share.ts
  src/assets/constant/constant.ts
  src/assets/record_icons/crown.svg
  src/assets/record_icons/gift.svg
  src/assets/record_icons/heart.svg
  src/assets/record_icons/like.svg
  src/assets/record_icons/lock.svg
  src/assets/record_icons/medal.svg
  src/assets/record_icons/moon.svg
  src/assets/record_icons/music.svg
  src/assets/record_icons/rocket.svg
  src/assets/record_icons/speechbubble.svg
  src/assets/record_icons/trashcan.svg
  src/assets/record_icons/umbrella.svg
  src/assets/record_icons/wine.svg
  src/assets/sharing_img.svg
  src/components/Alert.tsx
  src/components/NavbarItem.tsx
  src/index.css
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/EditModal.tsx
  src/pages/DetailRecord/ImageContainer.tsx
  src/pages/DetailRecord/NestedReplyList.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ReplyList.tsx
  src/pages/DetailRecord/getCreatedDate.ts
  src/pages/MyRecord/MemoryRecordItem.tsx
  src/pages/MyRecord/MyRecordCalendar.tsx
  src/pages/MyRecord/TodayRecord.tsx
  src/pages/SignUp/SignUp.tsx
  src/react-query/hooks/useAuth.ts
  src/react-query/hooks/useMyRecord.ts
  src/routes/protectedRoute.tsx
  src/store/atom.ts
Labels: 🎁 Delivery

#168 [FE-161] feat: 댓글 수정 추가, QA 버그 수정
  src/apis/reply.ts
  src/apis/share.ts
  src/components/BackButton.tsx
  src/components/Chip.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/NestedReplyList.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ShareModal.tsx
  src/store/atom.ts
Labels: ✨ Feature, 🐞 Bug

#166 [FE-169] design: 추억 레코드 댓글 없을 때 멘트 변경
  src/pages/MyRecord/MemoryRecordItem.tsx
Labels: 🧑‍🎨 Style

#167 [FE-170] design: 레코딧으로 이동 버튼 디자인 수정
  src/pages/NotFound/NotFound.tsx
Labels: 🧑‍🎨 Style

#170 [FE-172] feat: 엔터키 구현, 답글 수정 구현
  src/pages/AddRecord/AddRecord.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/NestedReplyList.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
Labels: ✨ Feature, 🐞 Bug

#169 [FE-167]fix: QA에러 수정
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordColor.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/store/atom.ts
Labels: 🐞 Bug, 🔨 Refactor

#172 fix: 답글 화살표 에러 수정
  src/pages/DetailRecord/ReplyItem.tsx
Labels: 🐞 Bug

#171 [FE-173]feat: 수정모드일때 수정불가능한것들 회색처리
  src/components/Chip.tsx
  src/components/MainCategoryTap.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
Labels: ✨ Feature

#173 [FE-174]feat: 레코드 삭제시 마이레코드로 이동
  src/pages/DetailRecord/DetailRecord.tsx
Labels: ✨ Feature

#174 fix: 수정모드일때 br 태그 수정
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/pages/DetailRecord/ReplyInput.tsx
Labels: 🐞 Bug

#175 [Fe-175]fix: 수정페이지 이동했을때 변경안하면 보라색으로 바뀜
  src/pages/AddRecord/AddRecord.tsx
Labels: 🐞 Bug

#176 [FE-171]fix: 레코드 추가후 수정했을때 카테고리 적용안되는 버그
  src/pages/AddRecord/AddRecordCategory.tsx
Labels: 🐞 Bug

#177 fix: 마이레코드 br 태그 버그 수정
  src/pages/MyRecord/MemoryRecordItem.tsx
Labels: 🐞 Bug

#178 [FE-176]feat: 수정모드일때 제목 색깔 변경
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordTitle.tsx
Labels: ✨ Feature

#180 [FE-177]fix: 수정접근하고 사진 삭제하고 다시추가하면 추가된게 이미지로 안보임
  src/pages/AddRecord/AddRecordFile.tsx
Labels: 🐞 Bug

#181 [fix] design: 레코드 추가/수정 실패 시 멘트 변경
  src/pages/AddRecord/AddRecord.tsx
Labels: 🐞 Bug

#179 [release] 상용 서버 배포 - 사용자 배포
  src/apis/reply.ts
  src/apis/share.ts
  src/components/BackButton.tsx
  src/components/Chip.tsx
  src/components/MainCategoryTap.tsx
  src/pages/AddRecord/AddRecord.tsx
  src/pages/AddRecord/AddRecordCategory.tsx
  src/pages/AddRecord/AddRecordColor.tsx
  src/pages/AddRecord/AddRecordFile.tsx
  src/pages/AddRecord/AddRecordIcon.tsx
  src/pages/AddRecord/AddRecordInput.tsx
  src/pages/AddRecord/AddRecordTextArea.tsx
  src/pages/AddRecord/AddRecordTitle.tsx
  src/pages/DetailRecord/DetailRecord.tsx
  src/pages/DetailRecord/NestedReplyList.tsx
  src/pages/DetailRecord/ReplyInput.tsx
  src/pages/DetailRecord/ReplyItem.tsx
  src/pages/DetailRecord/ShareModal.tsx
  src/pages/MyRecord/MemoryRecordItem.tsx
  src/pages/NotFound/NotFound.tsx
  src/store/atom.ts
Labels: 🎁 Delivery

#182 hotfix : 뒤로가기, 앞으로가기시 input 모드 데이터 남아있는 버그 수정
  package-lock.json
  package.json
  src/pages/DetailRecord/DetailRecord.tsx
Labels: 🐞 Bug
